### ISSUE TITLE
Error on module import

### ISSUE THREAD

**Issue by KingCrims0** [amadeus4dev/amadeus-python#122]
Hi,

Hope you're doing well

I'm trying to use the amadeus api with Python but i'm getting an error
I followed all the step in the readme file but whenever i run my python script, i get an error 'cannot import name Client'
It's the same for 'ResponseError' too

Traceback (most recent call last):
  File "amadeus.py", line 1, in <module>
    from amadeus import Client,ResponseError
  File "/mnt/c/wamp64/www/python/amadeus.py", line 1, in <module>
    from amadeus import Client,ResponseError
ImportError: cannot import name Client

I'm using pip 21.1.2 and Python 3.7 and i'm on Windows 10

Maybe you can help me ?
I don't know what i'm doing wrong.

Thanks in advance

**Comment by tsolakoua** [comment]
Hello @KingCrims0, which version of the Python SDK do you use? Could you share it with us your script to check out on our side?

**Comment by tsolakoua** [comment]
Closing this due to inactivity and not enough data to investigate.
